services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - NGINX_AUTORELOAD=true
    volumes:
      - ./config/nginx.conf:/config/nginx/site-confs/default.conf:ro
      - ./front/dist/front/browser:/config/www:ro
    ports:
      - 80:80
    restart: always